# For more info on HTTP files go to https://aka.ms/vs/httpfile
@Host_Address = {{Host_Address}}

PUT {{Host_Address}}/move/absolute/x/0.1

################################################################################
# Pol Axis Hand Terminal
################################################################################
### Incremental Move
PUT {{Host_Address}}/move/relative/pol/1

### Absolute Move

PUT {{Host_Address}}/move/absolute/pol/10

### Reference (Offset)

PUT {{Host_Address}}/reference/pol/0

### Home 

PUT {{Host_Address}}/home/pol

### Quick Stop 

PUT {{Host_Address}}/quickstop/pol

### Bring XY Axis
                  
PUT {{Host_Address}}/bringxy

### Z Axis Home
                  
PUT {{Host_Address}}/home/z

### Z Axis Reference
                  
PUT {{Host_Address}}/move/relative/z/0.1
